### PR TITLE
Added 2 Dev 👨🏻‍💻 Jokes

### PR DESCRIPTION
**Pull request by anupamhaldkar**

### CODE REVIEW

**Comment by mohitrakhade20** [comment]
format properly

**Comment by anupamhaldkar** [comment]
Do I need to use short form to(QnA) @mohitrakhade20

**Review by anupamhaldkar — COMMENTED** [review]
I reformatted it kindly accept @mohitrakhade20

**Review by mohitrakhade20 — COMMENTED** [review]
cool

**Pull request merged**
